markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:year/:month/:day/:title/
url: http://4lver.github.io
author: 4lver
#pygments: true
highlighter: pygments
safe: true
paginate: 16
auto: true

